apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ek2qb9vum-go
  janus-idp.io/tekton: ek2qb9vum-go
  backstage.io/kubernetes-id: ek2qb9vum-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ek2qb9vum-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
