apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ek2qb9vum-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ek2qb9vum-go 
  name: ek2qb9vum-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ek2qb9vum-go 
